import React, { useState } from 'react';
import { Sparkles, Clock, Play, RotateCcw, AlertCircle, Film, ArrowRight, CheckCircle, Loader2 } from 'lucide-react';
import { PRESET_STYLES, VideoStyle, VideoProject, PRESET_VOICES } from '../types';

interface StudioCreateProps {
  onVideoGenerated: (project: VideoProject) => void;
  activeVideo: VideoProject | null;
  setActiveVideo: (video: VideoProject) => void;
  setActiveTab: (tab: string) => void;
  currentTier?: 'Free' | 'Pro' | 'VIP';
  onOpenBilling?: () => void;
}

export default function StudioCreate({ 
  onVideoGenerated, 
  activeVideo, 
  setActiveVideo, 
  setActiveTab,
  currentTier = 'Free',
  onOpenBilling
}: StudioCreateProps) {
  const [prompt, setPrompt] = useState('');
  const [selectedStyle, setSelectedStyle] = useState('cinematic');
  const [customStyleText, setCustomStyleText] = useState('');
  const [aspectRatio, setAspectRatio] = useState('9:16');
  const [customRatio, setCustomRatio] = useState('');
  const [duration, setDuration] = useState(30); // in seconds
  const [consistentStyle, setConsistentStyle] = useState(true);
  const [selectedVoice, setSelectedVoice] = useState('deep_cinema');

  // Optimization & Generation State
  const [isOptimizing, setIsOptimizing] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [optPromptText, setOptPromptText] = useState('');
  const [generationProgress, setGenerationProgress] = useState(0);
  const [queuePosition, setQueuePosition] = useState(0);
  const [completedVideo, setCompletedVideo] = useState<VideoProject | null>(null);

  // Optimize prompt handler
  const handleOptimizePrompt = async () => {
    if (!prompt.trim()) return;
    setIsOptimizing(true);
    try {
      const response = await fetch('/api/optimize-prompt', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ prompt, style: selectedStyle })
      });
      const data = await response.json();
      setOptPromptText(data.optimizedPrompt);
    } catch (err) {
      // Inline Fallback modifier
      setOptPromptText(`[Optimized Style] ${prompt}. Extreme detail, 4K rendering high performance aspect ratio, gorgeous dynamic focal plane lighting.`);
    } finally {
      setIsOptimizing(false);
    }
  };

  // Start Generation Simulation
  const handleGenerateVideo = async () => {
    const finalPrompt = optPromptText || prompt;
    if (!finalPrompt.trim()) return;

    setIsGenerating(true);
    setGenerationProgress(2);
    setQueuePosition(4); // simulate cue position

    // Fetch Script & Subtitles from Backend
    let generatedMeta: any = {};
    try {
      const response = await fetch('/api/generate-script', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          prompt: finalPrompt,
          style: selectedStyle,
          duration,
          aspectRatio: aspectRatio === 'custom' ? customRatio : aspectRatio
        })
      });
      generatedMeta = await response.json();
    } catch {
      generatedMeta = {
        title: `Visualizing ${prompt.slice(0, 20)}`,
        description: `Stunning AI simulation for ${prompt}. Crafted on the fly.`,
        hashtags: ['#ai', '#viral', '#generation'],
        scenePlan: [
          { timeStart: 0, timeEnd: duration / 2, description: 'Part 1', subtitle: 'This is the opening scene generated by local forge core.' },
          { timeStart: duration / 2, timeEnd: duration, description: 'Part 2', subtitle: 'Pushing the boundary of viral video retention.' }
        ]
      };
    }

    // Progress Loop Animation
    const totalTime = 6000; // 6 seconds simulation
    const intervalTime = 150;
    let elapsed = 0;

    const timer = setInterval(() => {
      elapsed += intervalTime;
      const progressPercent = Math.min(Math.floor((elapsed / totalTime) * 100), 99);
      setGenerationProgress(progressPercent);

      // Sift queue
      if (progressPercent > 30 && progressPercent < 60) setQueuePosition(2);
      if (progressPercent >= 75) setQueuePosition(1);

      if (elapsed >= totalTime) {
        clearInterval(timer);
        
        // Complete generation!
        const generatedVideo: VideoProject = {
          id: 'v-' + Math.floor(Math.random() * 1000000),
          prompt: finalPrompt,
          style: selectedStyle,
          aspectRatio,
          customRatio: aspectRatio === 'custom' ? customRatio : undefined,
          duration,
          title: generatedMeta.title || 'Dynamic Viral Masterpiece',
          description: generatedMeta.description || 'Viral script simulation powered by AI core layers.',
          hashtags: generatedMeta.hashtags || ['#AIVideo', '#ViralForge'],
          thumbnail: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=300&q=80',
          videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-spiral-of-colored-light-beams-45367-large.mp4',
          status: 'Draft',
          progress: 100,
          queuePosition: 0,
          estTime: 'Completed',
          consistentStyle,
          voiceId: selectedVoice,
          targetPlatforms: [],
          targetAccounts: [],
          subtitles: (generatedMeta.scenePlan || []).map((scene: any, i: number) => ({
            id: `sub-scene-${i}`,
            timeStart: scene.timeStart,
            timeEnd: scene.timeEnd,
            text: scene.subtitle,
            effect: 'typewriter'
          })),
          volumeLevel: 100,
          musicVolume: 50,
          speed: 1.0,
          brightness: 100,
          contrast: 100,
          saturation: 100,
          lutFilter: 'none'
        };

        setGenerationProgress(100);
        setCompletedVideo(generatedVideo);
        onVideoGenerated(generatedVideo);
        setIsGenerating(false);
      }
    }, intervalTime);
  };

  const loadPromptPreset = (txt: string) => {
    setPrompt(txt);
    setOptPromptText('');
  };

  return (
    <div id="ai-video-studio-container" className="grid grid-cols-1 lg:grid-cols-12 gap-6">
      {/* Creation Configuration Area (Left) */}
      <div className="lg:col-span-7 space-y-6">
        <div className="rounded-2xl border border-white/10 bg-white/5 p-6 backdrop-blur-xl relative overflow-hidden">
          <div className="absolute top-0 right-0 h-40 w-40 bg-violet-600/10 rounded-full filter blur-3xl" />
          
          <div className="flex items-center justify-between mb-4">
            <h3 className="text-lg font-bold text-white flex items-center gap-2">
              <Sparkles className="h-5 w-5 text-violet-400" /> Script & Visual Directive
            </h3>
            <span className="text-xs text-violet-400 font-mono">Dynamic Scene Composer</span>
          </div>

          <label className="block text-xs font-semibold text-gray-400 uppercase tracking-wider mb-2">
            AI Prompt Instruction
          </label>
          <div className="relative">
            <textarea
              id="prompt-textarea"
              value={prompt}
              onChange={(e) => {
                setPrompt(e.target.value);
                setOptPromptText('');
              }}
              placeholder="Describe what you want to happen in the video in vivid detail (e.g. 'Golden retriever puppy navigating a beautiful sunflower maze holding a small camera')..."
              rows={4}
              className="w-full rounded-xl bg-black/40 border border-white/10 p-3.5 pr-20 text-sm text-white focus:outline-none focus:border-violet-500 transition duration-200 placeholder-gray-500 resize-none min-h-[100px]"
            />
            {prompt.trim() !== '' && (
              <button
                id="optimize-prompt-btn"
                onClick={handleOptimizePrompt}
                disabled={isOptimizing}
                className="absolute bottom-3 right-3 flex items-center gap-1 bg-gradient-to-r from-violet-600 to-cyan-500 hover:from-violet-500 hover:to-cyan-400 transition text-[11px] font-bold text-white px-3 py-1.5 rounded-lg border border-white/10 disabled:opacity-50 cursor-pointer shadow-md"
              >
                {isOptimizing ? (
                  <>
                    <Loader2 className="h-3 w-3 animate-spin" /> Optimizing...
                  </>
                ) : (
                  <>
                    <Sparkles className="h-3 w-3" /> Optimize
                  </>
                )}
              </button>
            )}
          </div>

          {/* Prompt Presets helper */}
          <div className="mt-3 flex flex-wrap gap-2 items-center">
            <span className="text-[10px] text-gray-400 uppercase font-bold">Presets:</span>
            {[
              "Cinematic drone loop of futuristic floating villa",
              "Cyberpunk hacker coding with visual neon HUD elements",
              "Cute kitten catching floating glowing space fish",
              "Splashing slow-mo strawberry juice macro showcase"
            ].map((p, idx) => (
              <button
                key={idx}
                type="button"
                onClick={() => loadPromptPreset(p)}
                className="text-[11px] text-gray-300 bg-white/5 border border-white/5 hover:border-violet-500/50 hover:bg-violet-950/20 px-2.5 py-1 rounded-md transition duration-150 cursor-pointer"
              >
                {p.slice(0, 32)}...
              </button>
            ))}
          </div>

          {/* Optimized Prompt Display */}
          {optPromptText && (
            <div className="mt-4 p-4 rounded-xl bg-violet-950/20 border border-violet-500/30 text-xs text-gray-200 space-y-1 relative animate-fade-in">
              <span className="absolute -top-2.5 left-3 bg-violet-900 border border-violet-500/40 text-[9px] font-black tracking-widest text-violet-300 uppercase px-1.5 rounded">
                Gemini Prompt Optimization Built
              </span>
              <p className="mt-1 leading-relaxed italic">{optPromptText}</p>
              <div className="flex justify-end gap-2 text-[10px] text-violet-400 font-mono">
                <span>Continuity Multiplier: Active</span>
              </div>
            </div>
          )}

          {/* Consistent Style Engine Toggle */}
          <div className="mt-6 p-4 rounded-xl bg-white/5 border border-white/10 flex items-center justify-between">
            <div className="space-y-1 pr-4">
              <span className="text-xs font-bold text-white flex items-center gap-1.5">
                👑 Style Consistency Memory Engine
              </span>
              <p className="text-[11px] text-gray-400">
                Locks identical seed generation matrices and facial style vectors across multiple continuous scenes to prevent character shifting.
              </p>
            </div>
            <label className="relative inline-flex items-center cursor-pointer">
              <input 
                id="consistency-toggle"
                type="checkbox" 
                checked={consistentStyle} 
                onChange={(e) => setConsistentStyle(e.target.checked)}
                className="sr-only peer" 
              />
              <div className="w-11 h-6 bg-white/10 peer-focus:outline-none rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-gradient-to-r peer-checked:from-violet-600 peer-checked:to-cyan-400"></div>
            </label>
          </div>
        </div>

        {/* Aspect Ratio Options */}
        <div className="rounded-2xl border border-white/10 bg-white/5 p-6 backdrop-blur-xl">
          <h4 className="text-xs font-bold text-gray-400 uppercase tracking-widest mb-3 flex items-center gap-2">
            <Film className="h-4 w-4 text-violet-400" /> Dimension Layout Ratio
          </h4>
          <div className="grid grid-cols-3 sm:grid-cols-6 gap-2">
            {[
              { id: '9:16', name: '9:16 vertical', label: 'Shorts/Reels' },
              { id: '1:1', name: '1:1 square', label: 'Instagram' },
              { id: '16:9', name: '16:9 wide', label: 'YouTube' },
              { id: '4:5', name: '4:5 tall', label: 'Facebook' },
              { id: '21:9', name: '21:9 ultra', label: 'Cinematic' },
              { id: 'custom', name: 'Custom', label: 'Ratio Input' }
            ].map((ratio) => (
              <button
                key={ratio.id}
                id={`ratio-${ratio.id}`}
                onClick={() => setAspectRatio(ratio.id)}
                type="button"
                className={`flex flex-col items-center justify-center p-2.5 rounded-xl border text-center transition duration-200 cursor-pointer ${
                  aspectRatio === ratio.id
                    ? 'border-cyan-400 bg-cyan-950/20 text-cyan-300'
                    : 'border-white/10 bg-black/20 hover:bg-white/5 text-gray-400 hover:text-white'
                }`}
              >
                <span className="text-sm font-bold">{ratio.id}</span>
                <span className="text-[9px] font-medium opacity-80 whitespace-nowrap">{ratio.label}</span>
              </button>
            ))}
          </div>

          {aspectRatio === 'custom' && (
            <div className="mt-3 animate-fade-in">
              <input
                id="custom-ratio-input"
                type="text"
                placeholder="e.g. 2.39:1 or 4:3"
                value={customRatio}
                onChange={(e) => setCustomRatio(e.target.value)}
                className="w-full max-w-[200px] rounded-lg bg-black/40 border border-white/10 p-2 text-xs text-white focus:outline-none focus:border-cyan-400"
              />
            </div>
          )}
        </div>

        {/* Duration Options */}
        <div className="rounded-2xl border border-white/10 bg-white/5 p-6 backdrop-blur-xl">
          <div className="flex items-center justify-between mb-3">
            <h4 className="text-xs font-bold text-gray-400 uppercase tracking-widest flex items-center gap-2">
              <Clock className="h-4 w-4 text-violet-400" /> Target Video Duration
            </h4>
            <span className="text-xs font-mono font-bold text-violet-400 bg-violet-950/40 px-2 py-0.5 rounded border border-violet-500/20">
              {duration >= 60 ? `${Math.floor(duration / 60)} min` : `${duration} seconds`}
            </span>
          </div>

          <div className="grid grid-cols-4 sm:grid-cols-7 gap-1.5 mb-4">
            {[15, 30, 60, 180, 300, 600, 900].map((d) => (
              <button
                key={d}
                type="button"
                onClick={() => setDuration(d)}
                className={`py-1.5 rounded-lg text-xs font-bold transition duration-200 cursor-pointer text-center ${
                  duration === d
                    ? 'bg-violet-600 border border-violet-400 text-white'
                    : 'bg-white/5 border border-white/5 hover:bg-[#121220] hover:border-white/10 text-gray-300'
                }`}
              >
                {d >= 60 ? `${d / 60}m` : `${d}s`}
              </button>
            ))}
          </div>
          {duration === 900 && (
            <div className="rounded-lg bg-cyan-950/20 border border-cyan-500/20 p-2.5 text-[11px] text-cyan-200/90 flex gap-2">
              <AlertCircle className="h-4 w-4 shrink-0 text-cyan-400" />
              <p>
                <strong>Flexible VIP Duration:</strong> 15 minutes is optimized for a single rendering sequence. As an Unlimited VIP member, you can chain as many continuous clips as you like to construct infinite footage.
              </p>
            </div>
          )}
        </div>

        {/* AI Voice Narration config block - Moved to Dedicated Speech Engine */}
        <div className="rounded-2xl border border-white/10 bg-gradient-to-br from-[#12101b] to-[#0a0910] p-6 backdrop-blur-xl space-y-4">
          <div className="flex items-center justify-between">
            <h4 className="text-xs font-bold text-gray-400 uppercase tracking-widest flex items-center gap-2">
              <span>🎙️ AI Vocal Narrator Speech Engine</span>
            </h4>
            <span className="text-[9px] font-mono text-violet-400 bg-violet-950/40 px-2 py-0.5 rounded border border-violet-500/25 font-bold">
              Upgraded Core
            </span>
          </div>
          <p className="text-[11.5px] text-gray-400 leading-relaxed">
            The high-fidelity **AI Vocal Narrator Speech Engine** has been promoted to a first-class dedicated workspace. You can now synthesize custom scripts, customize vocal speed & pitch, view live sound waveforms, and download high-resolution narration tracks.
          </p>

          <button
            type="button"
            onClick={() => setActiveTab('vocal-engine')}
            className="w-full py-2.5 px-3 bg-[#1e1933] border border-violet-500/30 hover:border-violet-400 text-white rounded-xl text-xs font-bold transition flex items-center justify-center gap-2 cursor-pointer shadow-md shadow-violet-950/20"
          >
            <span>Launch Dedicated AI Vocal Engine 🚀</span>
          </button>
        </div>
      </div>

      {/* Styled Grid and Queue Progress (Right) */}
      <div className="lg:col-span-5 space-y-6">
        {/* Style Library */}
        <div className="rounded-2xl border border-white/10 bg-white/5 p-6 backdrop-blur-xl">
          <h4 className="text-xs font-bold text-gray-400 uppercase tracking-widest mb-3 flex items-center justify-between">
            <span>Visual Concept Aesthetics</span>
            <span className="text-[10px] text-violet-400 font-mono">16 Studio Presets</span>
          </h4>

          <div className="grid grid-cols-2 xs:grid-cols-3 gap-2 max-h-[300px] overflow-y-auto pr-1">
            {PRESET_STYLES.map((style) => (
              <div
                key={style.id}
                onClick={() => setSelectedStyle(style.id)}
                className={`relative rounded-xl border p-2.5 flex flex-col justify-between h-20 transition duration-300 cursor-pointer overflow-hidden ${
                  selectedStyle === style.id
                    ? 'border-violet-500 bg-violet-950/25 ring-1 ring-violet-500'
                    : 'border-white/10 bg-black/20 hover:bg-white/5'
                }`}
              >
                {/* Visual Glow on selection */}
                {selectedStyle === style.id && (
                  <div className="absolute top-0 right-0 h-8 w-8 bg-violet-400/20 rounded-full blur-md" />
                )}

                <div className="flex items-center justify-between">
                  <span className="text-xl">{style.thumbnail}</span>
                  {selectedStyle === style.id && (
                    <span className="h-1.5 w-1.5 rounded-full bg-violet-400" />
                  )}
                </div>

                <div>
                  <h5 className="text-[11px] font-bold text-white leading-none mb-0.5">{style.name}</h5>
                  <p className="text-[8px] text-gray-400 truncate tracking-wide">{style.description}</p>
                </div>
              </div>
            ))}
          </div>

          {selectedStyle === 'custom-style' && (
            <div className="mt-3 p-3 rounded-lg bg-black/30 border border-white/10 space-y-2 animate-fade-in">
              <label className="text-[10px] text-gray-400 uppercase tracking-widest font-bold block">
                Custom Reference Aesthetic Upload
              </label>
              <div className="border border-dashed border-white/20 rounded-lg p-3 text-center cursor-pointer hover:bg-white/5 transition">
                <p className="text-[10px] text-gray-400">Drag & drop visual style stylecard image to lock aesthetic memory</p>
              </div>
            </div>
          )}
        </div>

        {/* Forge Generation Action Queue */}
        <div className="rounded-2xl border border-white/10 bg-white/5 p-6 backdrop-blur-xl relative">
          <h4 className="text-xs font-bold text-gray-400 uppercase tracking-widest mb-4">
            Rendering Operations Queue
          </h4>

          {!isGenerating && !completedVideo && (
            <div className="text-center py-10 space-y-3">
              <div className="mx-auto h-12 w-12 rounded-full border border-dashed border-white/20 flex items-center justify-center text-gray-500 text-lg">
                🎥
              </div>
              <div>
                <p className="text-xs text-gray-400 font-semibold">Ready to Forge Video sequence</p>
                <p className="text-[10px] text-gray-500">Configure prompt layers then trigger the forge button</p>
              </div>
              <button
                id="trigger-forge-btn"
                onClick={handleGenerateVideo}
                disabled={!prompt.trim()}
                className="w-full bg-gradient-to-r from-violet-600 to-cyan-500 hover:from-violet-500 hover:to-cyan-400 text-xs font-bold py-2.5 px-4 rounded-xl text-white transition duration-200 disabled:opacity-40 disabled:cursor-not-allowed cursor-pointer shadow-lg shadow-violet-500/15 flex items-center justify-center gap-1.5"
              >
                <Film className="h-4 w-4" /> Begin AI Video Generation
              </button>
            </div>
          )}

          {/* Active Generation Queue State */}
          {isGenerating && (
            <div className="space-y-4 py-2 animate-fade-in">
              <div className="flex items-center justify-between">
                <span className="flex items-center gap-2 text-xs font-bold text-white">
                  <span className="h-2 w-2 rounded-full bg-cyan-400 animate-ping" />
                  Generating Video Canvas
                </span>
                <span className="text-[11px] font-mono text-cyan-300">Queue Position: #{queuePosition}</span>
              </div>

              {/* Progress Slider */}
              <div className="space-y-1">
                <div className="flex justify-between text-[10px] text-gray-400 font-mono">
                  <span>Rendering frame packets</span>
                  <span className="font-bold text-white">{generationProgress}%</span>
                </div>
                <div className="h-2 w-full rounded-full bg-white/10 overflow-hidden relative border border-white/5">
                  <div 
                    className="h-full bg-gradient-to-r from-violet-500 to-cyan-400 transition-all duration-300"
                    style={{ width: `${generationProgress}%` }}
                  />
                </div>
              </div>

              {/* Queue Status metadata fields */}
              <div className="grid grid-cols-2 gap-2 text-[10px] font-mono bg-black/30 p-2.5 rounded-lg border border-white/5">
                <div>
                  <p className="text-gray-500">Style Profile:</p>
                  <p className="text-gray-300 font-bold capitalize">{selectedStyle}</p>
                </div>
                <div>
                  <p className="text-gray-500">Resolution Output:</p>
                  <p className="text-gray-300 font-bold">1080p CineReady</p>
                </div>
                <div>
                  <p className="text-gray-500">Duration Target:</p>
                  <p className="text-gray-300 font-bold">{duration} seconds</p>
                </div>
                <div>
                  <p className="text-gray-500">Continuity Memory:</p>
                  <p className={consistentStyle ? "text-emerald-400 font-bold" : "text-amber-500 font-bold"}>
                    {consistentStyle ? "Enabled" : "Disabled"}
                  </p>
                </div>
              </div>

              <div className="rounded-md bg-violet-950/10 border border-violet-500/20 p-2 text-[9px] text-violet-300 italic">
                ⏳ Veo Model layers are parsing visual descriptors. Please remain on page.
              </div>
            </div>
          )}

          {/* Finished Generation State & Preview Player */}
          {completedVideo && !isGenerating && (
            <div className="space-y-4 animate-fade-in">
              <div className="flex items-center justify-between">
                <span className="flex items-center gap-1.5 text-xs font-bold text-emerald-400">
                  <CheckCircle className="h-4 w-4" /> Render Generation Completed
                </span>
                <button
                  onClick={() => {
                    setPrompt('');
                    setOptPromptText('');
                    setCompletedVideo(null);
                  }}
                  className="text-[10px] text-gray-400 hover:text-white flex items-center gap-1 underline"
                >
                  <RotateCcw className="h-3 w-3" /> Gen New
                </button>
              </div>

              {/* Saved to Library success helper indicator */}
              <div className="rounded-xl bg-emerald-950/20 border border-emerald-500/20 p-2.5 text-[11px] text-emerald-300 flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <span className="h-2 w-2 rounded-full bg-emerald-400 animate-pulse shrink-0" />
                  <span>Auto-saved video to <strong>Ready Library</strong> database!</span>
                </div>
                <button
                  type="button"
                  onClick={() => setActiveTab('library')}
                  className="text-[10px] font-black text-cyan-400 hover:text-cyan-300 transition duration-150 shrink-0"
                >
                  Manage Assets 📁
                </button>
              </div>

              {/* Video Preview Frame */}
              <div className="relative rounded-xl overflow-hidden bg-black aspect-video border border-white/10 shadow-lg group">
                <video
                  id="preview-video-player"
                  src={completedVideo.videoUrl}
                  controls
                  className="w-full h-full object-cover"
                  poster={completedVideo.thumbnail}
                />
                <div className="absolute top-2 left-2 bg-black/60 backdrop-blur text-[9px] text-gray-300 px-1.5 py-0.5 rounded font-mono border border-white/5 pointer-events-none">
                  {completedVideo.aspectRatio} • {completedVideo.duration}s
                </div>
              </div>

              {/* Title & metadata preview */}
              <div className="space-y-1 p-2 bg-white/5 rounded-lg border border-white/5">
                <p className="text-xs font-bold text-white truncate">{completedVideo.title}</p>
                <p className="text-[10px] text-gray-400 line-clamp-1">{completedVideo.description}</p>
              </div>

              {/* Dual target calls to action -> Push to editor or view in library directly */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 pt-1">
                <button
                  id="forge-studio-cta"
                  onClick={() => {
                    setActiveVideo(completedVideo);
                    setActiveTab('forge');
                  }}
                  className="w-full flex items-center justify-center gap-2 bg-gradient-to-r from-violet-600 to-cyan-500 hover:from-violet-500 hover:to-cyan-400 text-xs font-bold py-2.5 px-4 rounded-xl text-white transition duration-300 cursor-pointer shadow-md"
                >
                  <span>Forge Studio Editor</span>
                  <ArrowRight className="h-4 w-4" />
                </button>

                <button
                  onClick={() => setActiveTab('library')}
                  className="w-full flex items-center justify-center gap-2 bg-white/5 border border-white/10 hover:bg-white/10 hover:border-white/20 text-xs font-bold py-2.5 px-4 rounded-xl text-gray-200 transition duration-300 cursor-pointer"
                >
                  <span>Go to Ready Library</span>
                  <span>📁</span>
                </button>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
